FROM iain17/meteord-base
MAINTAINER iain17

RUN apt-get -y install imagemagick
RUN apt-get -y install python-dev python-pip python-lxml libcairo2 libpango1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
RUN apt-get -y install wget
RUN pip install WeasyPrint